############################################################################
# boards/sparc/ajit1/ajit1-qemu/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

-include $(TOPDIR)/Make.defs

ASRCS =
CSRCS = ajit1_boot.c

include $(TOPDIR)/boards/Board.mk
